[project]
name = "test-vn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastrtc>=0.0.30",
    "gradio>=5.50.0",
    "numpy>=1.26.0",
]
